//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "famille_mtcs")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub code: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub designation: Option<String>,
    pub pix: Option<String>,
    pub letype: Option<String>,
    pub marque: Option<String>,
    pub prix_ttc: Option<String>,
    pub famille: Option<String>,
    pub depot: Option<String>,
    pub centre: Option<String>,
    pub reference: Option<String>,
    pub oem: Option<String>,
    pub marque_oem: Option<String>,
    pub keywords: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
