//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod centres;
pub mod contacts;
pub mod depots;
pub mod famille_mtcs;
pub mod familles;
pub mod letypes;
pub mod marque_oems;
pub mod marques;
pub mod users;
